# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-11:
    name: build on Node v11 (like server)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x] # 10.x, 12.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install dependencies
      run: npm ci
    - run: npm run test:js
    - run: npm run test:css
    - run: npm run build:css
    - run: npm run build:js
    - run: npm run test-server
      env:
        NODE_PORT: 3300
    - run: npm run github:integration
      env:
        NODE_PORT: 3300
